### ISSUE TITLE
Live request is not returning nothing

### ISSUE THREAD

**Issue by jmmercadom** [maxlinc/pacto-tutorial#1]
I just cloned the repo, then run:

``` ruby
bundle exec rake test:live
```

Then I see this error:

``` ruby
Failures:

  1) External request queries FactoryGirl contributors on Github
     Failure/Error: response = Net::HTTP.get(uri)
     EOFError:
       end of file reached
     # ./spec/external_request_spec.rb:7:in `block (2 levels) in <top (required)>'
```

From my understanding this is related with the nature of the protocol, we are using Net:HTTP to to an **https** request.

**Comment by maxlinc** [comment]
Which ruby are you using?

**Comment by jmmercadom** [comment]
1.9.3-p448

Jesús Mercado

**Comment by jmmercadom** [comment]
I just tested with 2.0.0-p353 and it worked by default.
So apparently Net::HTTP.get returns two different things depending of the ruby version =/.
Any thoughts?
The simplest way is to require at least 2.0.0 using .ruby-version file.
Or we can make it retro-compatible with 1.9.3 merging the PR.

**Comment by maxlinc** [comment]
If it was my app, I'd just upgrade :)

Since it's a demo, we should probably aim for wider compatibility.  Okay to
merge once you checkout the comments I added.

**Comment by jmmercadom** [comment]
Just updated the PR applying your suggestions. Push the button if you think is ok ;).
